//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BotDetect.Web.UI
{
    internal class captcha
    {
        internal bool Validate(string text)
        {
            throw new NotImplementedException();
        }
    }
}